### ISSUE TITLE
htmlContent.replace is not function

### ISSUE THREAD

**Issue by binzlink** [iminif/html-replace-webpack-plugin#1]
Unhandled rejection TypeError: htmlContent.replace is not a
function
at HtmlResWebpackPlugin.apply.compiler.plugin.compiler.plugin.Promise.resolv
e.then.then.HtmlResWebpackPlugin.buildStatsHtmlMode.HtmlResWebpackPlugin.printCh
unkName.HtmlResWebpackPlugin.buildStats.HtmlResWebpackPlugin.checkResource.HtmlR
esWebpackPlugin.injectAssets.injectChunks.map [as injectAssets] (E:\git\erp\node
_modules\html-res-webpack-plugin\index.js:475:28)

**Comment by asulaiman** [comment]
Works fine for me, make sure that you provide a regex instead of a string when you use a callback.
