### ISSUE TITLE
Error with webpack 4.12.0

### ISSUE THREAD

**Issue by mcgraphix** [iminif/html-replace-webpack-plugin#10]
When using this plugin, the following error is thrown to the terminal:

```
node_modules/html-replace-webpack-plugin/index.js:41
      compilation.hooks.htmlWebpackPluginBeforeHtmlProcessing.tapAsync('html-webpack-plugin-before-html-processing', this.replace)
                                                              ^

TypeError: Cannot read property 'tapAsync' of undefined
```
The webpack config just has it configured with

```
new HtmlReplaceWebpackPlugin([
      {
        pattern: '@@version',
        replacement: '1.0.0'
      }
    ])
```

Is there some required dependency for working with webpack 4.x?

**Comment by iminif** [comment]
@mcgraphix Currently you may need to rollback your webpack to lower version (e.g. v3.12.0) or upgrade to newest version of webpack.

**Comment by grantlucas** [comment]
Any plans on supporting Webpack 4? This issue is there on Webpack `4.16.5`

**Comment by iminif** [comment]
@grantlucas But it works fine on Webpack 4.16.5 in our testing project, make sure you‘v configured your Webpack correctly.

**Comment by iminif** [comment]
But it works fine on Webpack 4.16.5 in our testing project, make sure you‘v configured your Webpack correctly.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by eNepper** [comment]
I'm seeing this issue on webpack 4.20.2, I have a clean webpack config only with the html-replace-webpack-plugin. I have followed your own example on how to set up webpack + html-replace plugin and it's still doesn't work.

Error:
```
/node_modules/html-replace-webpack-plugin/index.js:41
      compilation.hooks.htmlWebpackPluginBeforeHtmlProcessing.tapAsync('html-webpack-plugin-before-html-processing', this.replace)
```

webpack.config.js
```
const HtmlReplaceWebPackPlugin = require('html-replace-webpack-plugin');

module.exports = {
    mode: 'development',
    entry: {
        index: './index.html'
    },
    output: {
        path: __dirname + '/dist',
        filename: 'index.html'
    },
    plugins: [
        new HtmlReplaceWebPackPlugin([
            {
                pattern: '@@title',
                replacement: 'My new title'
            }
        ])
    ]
};
```

From package.json:
```
"dependencies": {
    "html-replace-webpack-plugin": "^2.5.3",
    "webpack": "^4.20.2",
    "webpack-cli": "^3.1.2"
  }
```
