### ISSUE TITLE
compatibility with html-webpack-plugin

### ISSUE THREAD

**Issue by jpuck** [iminif/html-replace-webpack-plugin#2]
This doesn't seem to work with [`html-webpack-plugin`][1] so am I correct to assume this package also requires the html loader? A complete example would be helpful.

Thanks!

[1]:https://www.npmjs.com/package/html-webpack-plugin

**Comment by iminif** [comment]
So an early example is here: https://github.com/iminif/html-replace-webpack-plugin-howto, hope it helps for you!
